image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
checkoutLocation: "tiki"
tasks:
  - name: Tiki
    init: >
      mkdir -p /workspace/logs/apache;
      mkdir -p /workspace/logs/mysql;
      mkdir -p /workspace/mysql/data;
      sudo mysql_install_db --auth-root-authentication-method=normal;
      sudo service mysql start;
      mysqladmin -u root --password="" password gitpod;
      mysql -e "CREATE DATABASE tiki_db";
      sh setup.sh composer;
      php console.php database:configure --host localhost root gitpod tiki_db;
      php console.php database:install;      
    command: >
      sudo service mysql status;
      test $? -eq 0 || sudo service mysql start;
      apachectl start;
      cd $GITPOD_REPO_ROOT;


#vscode:
#  extensions:
#    - felixfbecker.php-debug
#    - bmewburn.vscode-intelephense-client