UPDATE tiki_menu_options SET icon = 'settings' WHERE name = 'Settings';
UPDATE tiki_menu_options SET icon = 'admin_search' WHERE name = 'Search';
UPDATE tiki_menu_options SET icon = 'admin_wiki' WHERE name = 'Wiki';
UPDATE tiki_menu_options SET icon = 'admin_blogs' WHERE name = 'Blogs';
UPDATE tiki_menu_options SET icon = 'admin_fgal' WHERE name = 'File Galleries';
UPDATE tiki_menu_options SET icon = 'articles' WHERE name = 'Articles';
UPDATE tiki_menu_options SET icon = 'admin_forums' WHERE name = 'Forums';
UPDATE tiki_menu_options SET icon = 'admin_trackers' WHERE name = 'Trackers';
UPDATE tiki_menu_options SET icon = 'admin_community' WHERE name = 'Community';
UPDATE tiki_menu_options SET icon = 'admin_faqs' WHERE name = 'FAQs';
UPDATE tiki_menu_options SET icon = 'admin_maps' WHERE name = 'Maps';
UPDATE tiki_menu_options SET icon = 'admin_messages' WHERE name = 'Newsletters';
UPDATE tiki_menu_options SET icon = 'admin_freetags' WHERE name = 'Tags';
UPDATE tiki_menu_options SET icon = 'admin_calendar' WHERE name = 'Calendar';
UPDATE tiki_menu_options SET icon = 'admin_user' WHERE name = 'My Account';
UPDATE tiki_menu_options SET icon = 'home' WHERE name = 'Home';
UPDATE tiki_menu_options SET icon = 'admin_category' WHERE name = 'Categories';
UPDATE tiki_menu_options SET icon = 'calculator' WHERE name = 'Accounting';
UPDATE tiki_menu_options SET icon = 'admin_directory' WHERE name = 'Directory';
UPDATE tiki_menu_options SET icon = 'receipt' WHERE name = 'Invoice';
UPDATE tiki_menu_options SET icon = 'pen' WHERE name = 'Quizzes';
UPDATE tiki_menu_options SET icon = 'clipboard-data' WHERE name = 'Reports';
UPDATE tiki_menu_options SET icon = 'admin_stats' WHERE name = 'Stats';
UPDATE tiki_menu_options SET icon = 'survey' WHERE name = 'Surveys';
UPDATE tiki_menu_options SET icon = 'spreadsheet' WHERE name = 'Spreadsheets';
UPDATE tiki_menu_options SET icon = 'file-spreadsheet' WHERE name = 'Timesheet';
UPDATE tiki_menu_options SET icon = 'globe' WHERE name = 'Users Map';
UPDATE tiki_menu_options SET icon = 'telephone' WHERE name = 'Contact Us';
UPDATE tiki_menu_options SET icon = 'bug' WHERE name = '(debug)';
UPDATE tiki_menu_options SET icon = 'kaltura' WHERE name = 'Kaltura Video';
UPDATE tiki_menu_options SET icon = 'calendar' WHERE name = 'Tiki Calendar';
UPDATE tiki_menu_options SET icon = 'wizard' WHERE name = 'User Wizard';