UPDATE tiki_menu_options SET icon = 'settings' WHERE name = 'Settings' AND icon = 'icon-configuration48x48';
UPDATE tiki_menu_options SET icon = 'admin_search' WHERE name = 'Search' AND icon = 'xfce4-appfinder48x48';
UPDATE tiki_menu_options SET icon = 'admin_wiki' WHERE name = 'Wiki' AND icon = 'wikipages48x48';
UPDATE tiki_menu_options SET icon = 'admin_blogs' WHERE name = 'Blogs' AND icon = 'blogs48x48';
UPDATE tiki_menu_options SET icon = 'admin_fgal' WHERE name = 'File Galleries' AND icon = 'file-manager48x48';
UPDATE tiki_menu_options SET icon = 'articles' WHERE name = 'Articles' AND icon = 'stock_bold48x48';
UPDATE tiki_menu_options SET icon = 'admin_forums' WHERE name = 'Forums' AND icon = 'stock_index48x48';
UPDATE tiki_menu_options SET icon = 'admin_trackers' WHERE name = 'Trackers' AND icon = 'gnome-settings-font48x48';
UPDATE tiki_menu_options SET icon = 'admin_community' WHERE name = 'Community' AND icon = 'users48x48';
UPDATE tiki_menu_options SET icon = 'admin_faqs' WHERE name = 'FAQs' AND icon = 'stock_dialog_question48x48';
UPDATE tiki_menu_options SET icon = 'admin_maps' WHERE name = 'Maps' AND icon = 'maps48x48';
UPDATE tiki_menu_options SET icon = 'admin_messages' WHERE name = 'Newsletters' AND icon = 'messages48x48';
UPDATE tiki_menu_options SET icon = 'admin_freetags' WHERE name = 'Tags' AND icon = 'vcard48x48';
UPDATE tiki_menu_options SET icon = 'admin_calendar' WHERE name = 'Calendar' AND icon = 'date48x48';
UPDATE tiki_menu_options SET icon = 'admin_user' WHERE name = 'My Account' AND icon = 'userfiles48x48';
UPDATE tiki_menu_options SET icon = 'home' WHERE name = 'Home' AND icon = 'home48x48';
UPDATE tiki_menu_options SET icon = 'admin_category' WHERE name = 'Categories' AND icon = 'categories48x48';
UPDATE tiki_menu_options SET icon = 'calculator' WHERE name = 'Accounting' AND icon = 'accounting48x48';
UPDATE tiki_menu_options SET icon = 'admin_directory' WHERE name = 'Directory' AND icon = 'directory48x48';
UPDATE tiki_menu_options SET icon = 'receipt' WHERE name = 'Invoice' AND icon = 'invoice48x48';
UPDATE tiki_menu_options SET icon = 'pen' WHERE name = 'Quizzes' AND icon = 'quizzes48x48';
UPDATE tiki_menu_options SET icon = 'clipboard-data' WHERE name = 'Reports' AND icon = 'reports48x48';
UPDATE tiki_menu_options SET icon = 'admin_stats' WHERE name = 'Stats' AND icon = 'stats48x48';
UPDATE tiki_menu_options SET icon = 'survey' WHERE name = 'Surveys' AND icon = 'surveys48x48';
UPDATE tiki_menu_options SET icon = 'spreadsheet' WHERE name = 'Spreadsheets' AND icon = 'spreadsheet48x48';
UPDATE tiki_menu_options SET icon = 'file-spreadsheet' WHERE name = 'Timesheet' AND icon = 'timesheet48x48';
UPDATE tiki_menu_options SET icon = 'globe' WHERE name = 'Users Map' AND icon = 'usersmap48x48';
UPDATE tiki_menu_options SET icon = 'telephone' WHERE name = 'Contact Us' AND icon = 'contactus48x48';
UPDATE tiki_menu_options SET icon = 'bug' WHERE name = '(debug)' AND icon = 'debug48x48';
UPDATE tiki_menu_options SET icon = 'kaltura' WHERE name = 'Kaltura Video' AND icon = 'kaltura48x48';
UPDATE tiki_menu_options SET icon = 'calendar' WHERE name = 'Tiki Calendar' AND icon = 'tikicalendar48x48';
UPDATE tiki_menu_options SET icon = 'wizard' WHERE name = 'User Wizard' AND icon = 'wizard_user48x48';