UPDATE tiki_menu_options SET icon = 'envelope' WHERE name = 'Messages';
UPDATE tiki_menu_options SET icon = 'check-square' WHERE name = 'Tasks';
UPDATE tiki_menu_options SET icon = 'bookmark' WHERE name = 'Bookmarks';
UPDATE tiki_menu_options SET icon = 'admin_module' WHERE name = 'Modules';
UPDATE tiki_menu_options SET icon = 'at' WHERE name = 'Webmail';
UPDATE tiki_menu_options SET icon = 'address-book' WHERE name = 'Contacts';
UPDATE tiki_menu_options SET icon = 'inbox' WHERE name = 'Mail-in';
UPDATE tiki_menu_options SET icon = 'sticky-note' WHERE name = 'Notepad';
UPDATE tiki_menu_options SET icon = 'file' WHERE name = 'My Files';
UPDATE tiki_menu_options SET icon = 'calendar' WHERE name = 'Mini Calendar';
UPDATE tiki_menu_options SET icon = 'bell' WHERE name = 'My Watches';
UPDATE tiki_menu_options SET icon = 'share-nodes' WHERE name = 'Friendship Network';
UPDATE tiki_menu_options SET icon = 'file' WHERE name = 'Wiki Home';
UPDATE tiki_menu_options SET icon = 'flask' WHERE name = 'Sandbox';
UPDATE tiki_menu_options SET icon = 'copy' WHERE name = 'Multiple Print';
UPDATE tiki_menu_options SET icon = 'share' WHERE name = 'Send Pages';
UPDATE tiki_menu_options SET icon = 'sitemap' WHERE name = 'Structures';
UPDATE tiki_menu_options SET icon = 'newspaper' WHERE name = 'Articles Home';
UPDATE tiki_menu_options SET icon = 'list' WHERE name = 'List Articles';
UPDATE tiki_menu_options SET icon = 'pen' WHERE name = 'Submit Article';
UPDATE tiki_menu_options SET icon = 'sliders' WHERE name = 'Admin Types';
UPDATE tiki_menu_options SET icon = 'folder' WHERE name = 'Admin Topics';
UPDATE tiki_menu_options SET icon = 'list' WHERE name = 'List Blogs';
UPDATE tiki_menu_options SET icon = 'bar-chart' WHERE name = 'Rankings';
UPDATE tiki_menu_options SET icon = 'edit' WHERE name = 'Create Blog';
UPDATE tiki_menu_options SET icon = 'edit' WHERE name = 'New Blog Post';
UPDATE tiki_menu_options SET icon = 'list' WHERE name = 'List Blog Posts';
UPDATE tiki_menu_options SET icon = 'comments' WHERE name = 'List Forums';
UPDATE tiki_menu_options SET icon = 'cog' WHERE name = 'Admin Forums';
UPDATE tiki_menu_options SET icon = 'link' WHERE name = 'Submit a new link';
UPDATE tiki_menu_options SET icon = 'globe' WHERE name = 'Browse Directory';
UPDATE tiki_menu_options SET icon = 'tools' WHERE name = 'Admin Directory';
UPDATE tiki_menu_options SET icon = 'images' WHERE name = 'List Galleries';
UPDATE tiki_menu_options SET icon = 'upload' WHERE name = 'Upload File';
UPDATE tiki_menu_options SET icon = 'clipboard' WHERE name = 'List Quizzes';
UPDATE tiki_menu_options SET icon = 'bar-chart' WHERE name = 'Quiz Stats';
UPDATE tiki_menu_options SET icon = 'bar-chart' WHERE name = 'List Surveys';
UPDATE tiki_menu_options SET icon = 'video' WHERE name = 'List Media';
UPDATE tiki_menu_options SET icon = 'cogs' WHERE name = 'Live Support';
UPDATE tiki_menu_options SET icon = 'admin_security' WHERE name = 'Security Admin';
UPDATE tiki_menu_options SET icon = 'file-code' WHERE name = 'HTML Pages';
UPDATE tiki_menu_options SET icon = 'tachometer-alt' WHERE name = 'Performance';
UPDATE tiki_menu_options SET icon = 'share' WHERE name = 'Social networks';
UPDATE tiki_menu_options SET icon = 'share' WHERE name = 'Tiki Share';
UPDATE tiki_menu_options SET icon = 'link' WHERE name = 'List Shared URLs';
UPDATE tiki_menu_options SET icon = 'desktop' WHERE name = 'Admin Icons Dashboard';
UPDATE tiki_menu_options SET icon = 'credit-card' WHERE name = 'Payments';
UPDATE tiki_menu_options SET icon = 'person' WHERE name = 'My Account Home';
UPDATE tiki_menu_options SET icon = 'gear' WHERE name = 'Preferences';
UPDATE tiki_menu_options SET icon = 'list' WHERE name = 'User Menu';
UPDATE tiki_menu_options SET icon = 'users' WHERE name = 'User List';
UPDATE tiki_menu_options SET icon = 'history' WHERE name = 'Last Changes';
UPDATE tiki_menu_options SET icon = 'file-text' WHERE name = 'List Pages';
UPDATE tiki_menu_options SET icon = 'plus' WHERE name = 'Create a Wiki Page';
UPDATE tiki_menu_options SET icon = 'question-circle' WHERE name = 'Orphan Pages';
UPDATE tiki_menu_options SET icon = 'inbox' WHERE name = 'Received Pages';
UPDATE tiki_menu_options SET icon = 'clipboard-list' WHERE name = 'View submissions';
UPDATE tiki_menu_options SET icon = 'clipboard-list' WHERE name = 'View Submissions';
UPDATE tiki_menu_options SET icon = 'plus' WHERE name = 'New Article';
UPDATE tiki_menu_options SET icon = 'send' WHERE name = 'Send Articles';
UPDATE tiki_menu_options SET icon = 'inbox' WHERE name = 'Received Articles';
UPDATE tiki_menu_options SET icon = 'cloud' WHERE name = 'Directory batch';
UPDATE tiki_menu_options SET icon = 'list-ol' WHERE name = 'List FAQs';
UPDATE tiki_menu_options SET icon = 'tools' WHERE name = 'Admin FAQs';
UPDATE tiki_menu_options SET icon = 'puzzle-piece' WHERE name = 'Admin Quizzes';
UPDATE tiki_menu_options SET icon = 'table' WHERE name = 'List Sheets';
UPDATE tiki_menu_options SET icon = 'tasks' WHERE name = 'List Trackers';
UPDATE tiki_menu_options SET icon = 'toggle-on' WHERE name = 'Offline mode';
UPDATE tiki_menu_options SET icon = 'table' WHERE name = 'Manage Tabular Formats';
UPDATE tiki_menu_options SET icon = 'robot' WHERE name = 'Machine Learning';
UPDATE tiki_menu_options SET icon = 'layer-group' WHERE name = 'List Models';
UPDATE tiki_menu_options SET icon = 'book' WHERE name = 'Accounting books';
UPDATE tiki_menu_options SET icon = 'check-square' WHERE name = 'Admin Surveys';
UPDATE tiki_menu_options SET icon = 'envelope' WHERE name = 'Send Newsletters';
UPDATE tiki_menu_options SET icon = 'file-alt' WHERE name = 'Admin Newsletters';
UPDATE tiki_menu_options SET icon = 'columns' WHERE name = ' Control Panels';
UPDATE tiki_menu_options SET icon = 'ban' WHERE name = 'Banning';
UPDATE tiki_menu_options SET icon = 'coins' WHERE name = 'Admin credits';
UPDATE tiki_menu_options SET icon = 'user' WHERE name = 'Users';
UPDATE tiki_menu_options SET icon = 'users' WHERE name = 'Groups';
UPDATE tiki_menu_options SET icon = 'cloud' WHERE name = 'External Pages Cache';
UPDATE tiki_menu_options SET icon = 'tag' WHERE name = 'Hotwords';
UPDATE tiki_menu_options SET icon = 'translate' WHERE name = 'Edit languages';
UPDATE tiki_menu_options SET icon = 'rss' WHERE name = 'External Feeds';
UPDATE tiki_menu_options SET icon = 'globe' WHERE name = 'External Wikis';
UPDATE tiki_menu_options SET icon = 'bars' WHERE name = 'Menus';
UPDATE tiki_menu_options SET icon = 'check-square' WHERE name = 'Polls';
UPDATE tiki_menu_options SET icon = 'bell' WHERE name = 'Mail Notifications';
UPDATE tiki_menu_options SET icon = 'bar-chart' WHERE name = 'Search Stats';
UPDATE tiki_menu_options SET icon = 'palette' WHERE name = 'Theme Control';
UPDATE tiki_menu_options SET icon = 'key' WHERE name = 'Tokens';
UPDATE tiki_menu_options SET icon = 'wrench' WHERE name = 'Toolbars';
UPDATE tiki_menu_options SET icon = 'project-diagram' WHERE name = 'Transitions';
UPDATE tiki_menu_options SET icon = 'image' WHERE name = 'Banners';
UPDATE tiki_menu_options SET icon = 'cubes' WHERE name = 'Dynamic content';
UPDATE tiki_menu_options SET icon = 'message' WHERE name = 'Shoutbox';
UPDATE tiki_menu_options SET icon = 'message' WHERE name = 'Shoutbox Words';
UPDATE tiki_menu_options SET icon = 'bar-chart' WHERE name = 'Referer Stats';
UPDATE tiki_menu_options SET icon = 'puzzle-piece' WHERE name = 'Integrator';
UPDATE tiki_menu_options SET icon = 'info-circle' WHERE name = 'phpinfo';
UPDATE tiki_menu_options SET icon = 'server' WHERE name = 'Tiki Cache/Sys Admin';
UPDATE tiki_menu_options SET icon = 'file-import' WHERE name = 'Tiki Importer';
UPDATE tiki_menu_options SET icon = 'th-list' WHERE name = 'Tiki Logs';
UPDATE tiki_menu_options SET icon = 'briefcase' WHERE name = 'Tiki Manager';
UPDATE tiki_menu_options SET icon = 'clipboard-list' WHERE name = 'Action Log';
UPDATE tiki_menu_options SET icon = 'file' WHERE name = 'Content Templates';
UPDATE tiki_menu_options SET icon = 'admin_comments' WHERE name = 'Comments';
UPDATE tiki_menu_options SET icon = 'award' WHERE name = 'Contribution';
UPDATE tiki_menu_options SET icon = 'key' WHERE name = 'Permissions';
UPDATE tiki_menu_options SET icon = 'eye' WHERE name = 'Perspectives';
UPDATE tiki_menu_options SET icon = 'calendar-check' WHERE name = 'Scheduler';
UPDATE tiki_menu_options SET icon = 'cloud' WHERE name = 'Webservices';
UPDATE tiki_menu_options SET icon = 'bookmarks' WHERE name = 'References';
UPDATE tiki_menu_options SET icon = 'route' WHERE name = 'Custom Routes';
UPDATE tiki_menu_options SET icon = 'list' WHERE name = 'List PeerTube Media';
UPDATE tiki_menu_options SET icon = 'upload' WHERE name = 'Upload PeerTube Video';
UPDATE tiki_menu_options SET icon = 'tasks' WHERE name = 'Queued Tasks';