#!/bin/bash
setup()
{
    export LC_ALL=C
    MY_PATH="`dirname \"$0\"`"
    MY_PATH="`( cd \"$MY_PATH\" && pwd )`"
    . $MY_PATH/tim-common
}

setup

for BRANCH in $BRANCHES; do
    cd $GIT_CACHE/$BRANCH/

    git fetch --all > /dev/null
    git reset --hard origin/$BRANCH > /dev/null
    git clean -fd > /dev/null

    touch $GIT_CACHE/$BRANCH.lock
    tar -czf $GIT_CACHE/tmp_$BRANCH.tgz . && mv $GIT_CACHE/tmp_$BRANCH.tgz $GIT_CACHE/$BRANCH.tar.gz
    /bin/rm $GIT_CACHE/$BRANCH.lock
done
