<?php

// (c) Copyright by authors of the Tiki Wiki CMS Groupware Project
//
// All Rights Reserved. See copyright.txt for details and a complete list of authors.
// Licensed under the GNU LESSER GENERAL PUBLIC LICENSE. See license.txt for details.
function prefs_forum_list()
{
    $forumSettingsHelp = 'Forum-Settings';
    $forumListingHelp = 'Forum-Listing';

    return [
        'forum_image_file_gallery' => [
            'name' => tr('Forum image file gallery'),
            'description' => tr('File gallery used to store images for forums'),
            'type' => 'text',
            'help' => $forumSettingsHelp,
            'default' => 0,
            'profile_reference' => 'file_gallery',
            'dependencies' => ['feature_file_galleries'],
        ],
        'forum_comments_no_title_prefix' => [
            'name' => tra("Do not start messages titles with 'Re:'"),
            'description' => tra("If enabled, reply message titles will not be prefixed with 'Re:'."),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
        ],
        'forum_match_regex' => [
            'name' => tra('Uploaded filenames must match regex'),
            'description' => tra('Only forum attachment filenames matching this PHP regular expression are allowed (for example: /\\.(txt|jpg|png|gif|pdf|doc|docx)$/i).'),
            'type' => 'text',
            'help' => $forumSettingsHelp,
            'size' => '20',
            'default' => '',
        ],
        'forum_thread_defaults_by_forum' => [
            'name' => tra('Manage thread defaults per-forum'),
            'description' => tra('Allow each forum to define its own default thread display settings (style, sort mode, and comments per page) instead of relying only on global forum defaults.'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
        ],
        'forum_thread_user_settings' => [
            'name' => tra('Display thread configuration bar'),
            'description' => tra('Show controls in forum threads that let users change messages per page, thread style, and sort mode for the current view.'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'hint' => tra('Allows users to override the defaults'),
            'default' => 'y',
        ],
        'forum_thread_user_settings_threshold' => [
            'name' => tra('Display the thread configuration bar only when the number of posts exceeds'),
            'description' => tra('Show the thread configuration bar only when the total number of posts in the thread is greater than this value.'),
            'type' => 'text',
            'size' => '5',
            'filter' => 'digits',
            'units' => tra('posts'),
            'help' => $forumSettingsHelp,
            'default' => 10,
                ],
        'forum_thread_user_settings_keep' => [
            'name' => tra('Keep settings for all forums during the user session'),
            'description' => tra('Reuse the user selected thread display settings across all forums for the duration of the current session.'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
            ],
        'forum_comments_per_page' => [
            'name' => tra('Number per page'),
            'description' => tra('Default number of comments shown per page in forum threads.'),
            'type' => 'text',
            'size' => '5',
            'filter' => 'digits',
            'help' => $forumSettingsHelp,
            'units' => tra('comments'),
            'default' => 20,
        ],
        'forum_thread_style' => [
            'name' => tra('Default style'),
            'description' => tra('Default display style used for forum threads (plain, threaded, or headers only).'),
            'type' => 'list',
            'options' => [
                'commentStyle_plain' => tra('Plain'),
                'commentStyle_threaded' => tra('Threaded'),
                'commentStyle_headers' => tra('Headers only'),
            ],
            'help' => $forumSettingsHelp,
            'default' => 'commentStyle_plain',
        ],
        'forum_thread_sort_mode' => [
            'name' => tra('Default sort mode'),
            'description' => tra('Default order used to sort posts within forum threads.'),
            'type' => 'list',
            'options' => [
                'commentDate_desc' => tra('Newest first'),
                'commentDate_asc' => tra('Oldest first'),
                'points_desc' => tra('Score'),
                'title_desc' => tra('Title (desc)'),
                'title_asc' => tra('Title (asc)'),
            ],
            'help' => $forumSettingsHelp,
            'default' => 'commentDate_asc',
        ],
        'forum_list_topics' => [
            'name' => tra('Topics'),
            'description' => tra('Show the topics count column in forum listings.'),
            'type' => 'flag',
            'help' => $forumListingHelp,
            'default' => 'n',
        ],
        'forum_list_posts' => [
            'name' => tra('Posts'),
            'description' => tra('Show the posts count column in forum listings.'),
            'type' => 'flag',
            'help' => $forumListingHelp,
            'default' => 'y',
        ],
        'forum_list_ppd' => [
            'name' => tra('Posts per day') . ' (PPD)',
            'description' => tra('Show the posts-per-day (PPD) column in forum listings.'),
            'type' => 'flag',
            'help' => $forumListingHelp,
            'default' => 'n',
        ],
        'forum_list_lastpost' => [
            'name' => tra('Last post'),
            'description' => tra('Show the last post column in forum listings.'),
            'type' => 'flag',
            'help' => $forumListingHelp,
            'default' => 'y',
        ],
        'forum_list_visits' => [
            'name' => tra('Visits'),
            'description' => tra('Show the visits count column in forum listings.'),
            'type' => 'flag',
            'help' => $forumListingHelp,
            'default' => 'y',
        ],
        'forum_list_desc' => [
            'name' => tra('Description'),
            'description' => tra('Show the description column in forum listings.'),
            'type' => 'flag',
            'help' => $forumListingHelp,
            'default' => 'y',
        ],
        'forum_list_description_len' => [
            'name' => tra('Description length'),
            'description' => tra('Maximum number of characters shown for forum descriptions in forum listings.'),
            'type' => 'text',
            'size' => '5',
            'help' => $forumListingHelp,
            'filter' => 'digits',
            'units' => tra('characters'),
            'default' => '240',
        ],
        'forum_reply_notitle' => [
            'name' => tra("Don't display forum thread titles"),
            'description' => tra("Titles of posts usually don't change because they are a direct reply to the parent post. This feature turns off the display of titles in edit forms and forum display."),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
        ],
        'forum_reply_forcetitle' => [
            'name' => tra('Require reply to have a title'),
            'description' => tra('Present an empty title input form and require it to be filled in before the forum post is submitted.'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
        ],
        'forum_quote_prevent_nesting' => [
            'name' => tra('Prevent Nesting of Quote wikiplugins when replying'),
            'description' => tra('Strips quote plugin in reply in order to prevent nesting of quote plugins.'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
            'dependencies' => ['feature_use_quoteplugin'],
        ],
        'forum_available_categories' => [
            'name' => tr('Forum post categories'),
            'description' => tr('Categories available in the category picker for forum posts.'),
            'help' => $forumListingHelp,
            'type' => 'text',
            'separator' => ',',
            'filter' => 'digits',
            'default' => [],
            'dependencies' => ['feature_categories'],
            'profile_reference' => 'category',
        ],
        'forum_category_selector_in_list' => [
            'name' => tr('Include category selector in forum list'),
            'description' => tr("Include a dropdown selector in the forum list to choose a category for the post."),
            'help' => $forumListingHelp,
            'type' => 'flag',
            'default' => 'n',
            'dependencies' => ['feature_categories'],
        ],
        'forum_inbound_mail_ignores_perms' => [
            'name' => tr('Allow inbound email posts from anyone'),
            'description' => tr('Allow messages from non-users in the forums using incoming messages from any email address.'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
        ],
        'forum_inbound_mail_parse_html' => [
            'name' => tr('Parse HTML in inbound email posts'),
            'description' => tr('Attempt to keep the formatting of HTML "rich text" emails if using WYSIWYG.'),
            'type' => 'flag',
            'default' => 'n',
            'help' => $forumSettingsHelp,
            'tags' => ['experimental'],
            'warning' => tra('Experimental') . ' ' . tra('Has problems with some HTML emails, especially those with table-based layouts.'),
            'dependencies' => ['feature_wysiwyg'],
        ],
        'forum_strip_wiki_syntax_outgoing' => [
            'name' => tr('Strip wiki markup from outgoing forum emails'),
            'description' => tr('Convert outgoing emails from forum posts to plain text.'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
            'dependencies' => ['feature_forum_parse'],
        ],
        'forum_moderator_notification' => [
            'name' => tr('Send moderation email'),
            'description' => tr('Send email to forum moderators when post is queued'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'y',
        ],
        'forum_moderator_email_approve' => [
            'name' => tr('Approve link in moderation email'),
            'description' => tr('Include a link for forum moderators to approve queue from email'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n',
            'dependencies' => ['forum_moderator_notification'],
        ],
        'forum_notifications_use_new_threads' => [
            'name' => tr('New email thread for each topic'),
            'description' => tr("If enabled each topic a forum will use it's own email thread, instead of all forum posts sharing the same one."),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'y',
        ],
        'forum_mask_emails' => [
            'name' => tr('Mask emails'),
            'description' => tr('Email information will be masked as "<2 letters>…@<2 letters>…"'),
            'type' => 'flag',
            'help' => $forumSettingsHelp,
            'default' => 'n'
        ],
    ];
}
