<?php

// (c) Copyright by authors of the Tiki Wiki CMS Groupware Project
//
// All Rights Reserved. See copyright.txt for details and a complete list of authors.
// Licensed under the GNU LESSER GENERAL PUBLIC LICENSE. See license.txt for details.
function prefs_xmpp_list()
{
    return [
        'xmpp_feature' => [
            'name' => tra('XMPP client (ConverseJS)'),
            'description' => tra('Integration with Converse.js XMPP client.'),
            'type' => 'flag',
            'keywords' => 'xmpp jabber converse conversejs chat',
            'help' => 'XMPP',
            'tags' => ['basic'],
            'default' => 'n',
            'extensions' => [
            ],
        ],
        'xmpp_server_host' => [
            'name' => tra('XMPP server domain'),
            'description' => tra('XMPP server domain'),
            'type' => 'text',
            'filter' => 'text',
            'hint' => tra('example.org'),
            'keywords' => 'xmpp converse conversejs chat',
            'size' => 40,
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_client_port' => [
            'name' => tra('XMPP client port'),
            'description' => tra('TCP port used to connect to the XMPP server (C2S)'),
            'type' => 'text',
            'filter' => 'int',
            'hint' => '5222',
            'tags' => ['basic'],
            'default' => '5222',
        ],
        'xmpp_muc_component_domain' => [
            'name' => tra('XMPP MUC Domain'),
            'description' => tra('Domain of the MUC (multi-user chat) service (used by both Openfire and Prosody)'),
            'type' => 'text',
            'filter' => 'text',
            'hint' => tra('conference.example.org'),
            'keywords' => 'xmpp converse conversejs chat',
            'size' => 40,
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_server_http_bind' => [
            'name' => tra('XMPP BOSH URL (http-bind)'),
            'description' => tra('Full URL to the http-bind endpoint (used by both Openfire and Prosody). Used only if no WebSocket URL is configured.'),
            'keywords' => 'xmpp converse conversejs chat',
            'type' => 'text',
            'size' => 40,
            'filter' => 'url',
            'hint' => tra('https://xmpp.example.org/http-bind/'),
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_auth_method' => [
            'name' => tra('Authentication method'),
            'description' => tra('The authentication method to be used by XMPP client'),
            'keywords' => 'xmpp converse conversejs chat auth',
            'type' => 'list',
            'tags' => ['basic'],
            'default' => '',
            'options' => [
                '' => tra('Plain'),
                'oauth' => tra('OAuth (uses Tiki as provider)'),
                'tikitoken' => tra('Openfire TikiToken'),
                'http' => tra('Prosody HTTP Auth'),
            ],
        ],
        'xmpp_openfire_allow_anonymous' => [
            'name' => tra('Allow anonymous'),
            'description' => tra('Allow anonymous users on Chat'),
            'type' => 'flag',
            'keywords' => 'xmpp jabber anonymous conversejs chat',
            'help' => 'XMPP',
            'tags' => ['basic'],
            'default' => 'n',
            'extensions' => [
            ],
        ],
        'xmpp_openfire_rest_api' => [
            'name' => tra('Openfire REST API endpoint'),
            'description' => tra('Full URL to API endpoint'),
            'keywords' => 'xmpp openfire restapi rest api chat',
            'type' => 'text',
            'size' => 40,
            'filter' => 'url',
            'hint' => tra('https://xmpp.example.org:9091/plugins/restapi/v1/'),
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_openfire_rest_api_username' => [
            'name' => tra('Rest API username'),
            'description' => tra('Username to allow Openfire API usage'),
            'keywords' => 'xmpp openfire restapi rest api chat',
            'type' => 'text',
            'size' => 40,
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_openfire_rest_api_password' => [
            'name' => tra('Rest API password'),
            'description' => tra('Password to allow Openfire API usage'),
            'keywords' => 'xmpp openfire restapi rest api chat',
            'type' => 'password',
            'size' => 40,
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_conversejs_debug' => [
            'name' => tra('ConverseJS Debug Mode'),
            'default' => 'n',
            'description' => tra('Enables more logging, e.g. XML stanzas and error tracebacks to the JavaScript Console'),
            'keywords' => 'xmpp jabber openfire chat',
            'type' => 'flag',
        ],
        'xmpp_conversejs_init_json' => [
            'name' => tra('ConverseJS Extra Settings'),
            'description' => tra('JSON format object defining extra optional settings to initialize ConverseJS'),
            'type' => 'textarea',
            'filter' => 'text',
            'keywords' => 'xmpp jabber openfire converse chat',
            'size' => 10,
            'default' => '',
        ],
        'xmpp_conversejs_always_load' => [
            'name' => tra('Always Load ConverseJS'),
            'default' => 'n',
            'description' => tra('Adds the ConverseJS Javascript and CSS files to every page.'),
            'keywords' => 'xmpp jabber openfire chat',
            'type' => 'flag',
            'dependencies' => ['xmpp_feature'],
        ],
        'xmpp_domain_users' => [
            'name' => tra('XMPP domain for registered users'),
            'description' => tra('Domain used by XMPP server for authenticated members'),
            'type' => 'text',
            'filter' => 'text',
            'hint' => 'xmpp.example.org',
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_domain_guest' => [
            'name' => tra('XMPP domain for anonymous visitors'),
            'description' => tra('Domain used by XMPP server for guest/anonymous logins'),
            'type' => 'text',
            'filter' => 'text',
            'hint' => 'guest.example.org',
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_anonymous_mode' => [
            'name' => tra('Anonymous visitor mode'),
            'description' => tra('Choose if anonymous visitors join a community room or a dedicated support room'),
            'type' => 'list',
            'options' => [
                'community' => tra('Community room'),
                'support' => tra('Personalized support'),
            ],
            'default' => 'community',
            'tags' => ['basic'],
        ],
        'xmpp_anonymous_allow_custom_nickname' => [
            'name' => tra('Allow anonymous visitors to choose a nickname'),
            'description' => tra('When enabled, anonymous visitors are prompted to choose their chat nickname before sending messages. When disabled, Tiki uses an automatic visitor nickname.'),
            'type' => 'flag',
            'tags' => ['basic'],
            'default' => 'n',
        ],
        'xmpp_ws_url' => [
            'name' => tra('XMPP WebSocket URL'),
            'description' => tra('WebSocket endpoint for ConverseJS. If set, this takes precedence over the BOSH (http-bind) URL.'),
            'type' => 'text',
            'filter' => 'url',
            'hint' => 'wss://xmpp.example.org/xmpp-websocket',
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_anonymous_room' => [
            'name' => tra('Default anonymous chat room'),
            'description' => tra('Room where guests are automatically joined'),
            'type' => 'text',
            'filter' => 'text',
            'hint' => 'community@conference.example.org',
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_anonymous_support_room' => [
            'name' => tra('Anonymous support room'),
            'description' => tra('Room where guests are joined when anonymous mode is set to personalized support'),
            'type' => 'text',
            'filter' => 'text',
            'hint' => 'support@conference.example.org',
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_registered_room' => [
            'name' => tra('Default registered chat room'),
            'description' => tra('Room where registered members are auto-joined'),
            'type' => 'text',
            'filter' => 'text',
            'hint' => 'registered@conference.example.org',
            'tags' => ['basic'],
            'default' => '',
        ],
        'xmpp_group_room_map' => [
            'name' => tra('Mapping Tiki groups to chat rooms'),
            'description' => tra('JSON mapping of Tiki groups to rooms'),
            'type' => 'textarea',
            'hint' => "{
                \"Registered\": \"registered@conference.example.org\",
                \"Translators\": \"translators@conference.example.org\"
            }",
            'default' => '',
            'tags' => ['advanced'],
        ],
        'xmpp_auto_join_strategy' => [
            'name' => tra('Auto-join strategy'),
            'description' => tra('Define how users are auto-joined into chat rooms'),
            'type' => 'list',
            'options' => [
                'by-groups' => tra('By groups'),
                'static' => tra('Static'),
                'none' => tra('Disabled'),
            ],
            'default' => 'by-groups',
            'tags' => ['basic'],
        ],
        'xmpp_shared_secret' => [
            'name' => tra('XMPP shared secret (HTTP auth)'),
            'description' => tra('Shared secret used to secure HTTP authentication requests between Prosody and Tiki. Must match the value configured in prosody.cfg.lua.'),
            'type' => 'password',
            'default' => '',
            'tags' => ['advanced'],
        ],
        'xmpp_cors_allowed_origins' => [
            'name' => tra('CORS allowed origins (comma-separated)'),
            'description' => tra('List of allowed origins (comma-separated URLs) for Cross-Origin Resource Sharing. Only requests from these origins will be accepted by the XMPP auth endpoint.'),
            'type' => 'text',
            'default' => '',
            'tags' => ['advanced'],
        ],
        'xmpp_admin_jid' => [
            'name' => tra('XMPP Admin JID'),
            'description' => tra('Full JID of XMPP admin (must be listed in Prosody admins)'),
            'type' => 'text',
            'hint' => 'admin@xmpp.example.org',
            'default' => '',
            'tags' => ['advanced'],
        ],
        'xmpp_admin_password' => [
            'name' => tra('XMPP Admin Password'),
            'description' => tra('Password of XMPP admin'),
            'type' => 'password',
            'default' => '',
            'tags' => ['advanced'],
        ],
    ];
}
