-- tiki_innodb.sql is run after tiki.sql if InnoDB is being installed
-- Do not include fulltext index definitions. The installer will include these when the current db engine supports fulltext search
