<?php

define("ROOT", realpath(__DIR__ . '/../..'));

const CHANGELOG_FILE = 'generated_changelog.md';
const REPO_URL = 'https://gitlab.com/tikiwiki/tiki';


$valid_tags = [
    // High priority
    'SEC', 'NEW', 'ENH', 'REM', 'MOD',
    // Medium priority
    'FIX', 'UX', 'UI', 'DB', 'UPD',
    // Low priority
    'REF', 'KIL', 'BP', 'TRA'
];

$section_map = [
    'NEW' => 'Additions of new features',
    'ENH' => 'Enhancement improvements',
    'REF' => 'Refactoring',
    'FIX' => 'Bug fixes',
    'SEC' => 'Security fixes',
    'REM' => 'Removals',
    'MOD' => 'Modifications',
    'UPD' => 'Dependency updates',
    'UX'  => 'User experience improvements',
    'DB'  => 'Database changes',
    'KIL' => 'Removal of obsolete files',
    'TRA' => 'Translation',
];

$low_priority_tags = ['FIX', 'REF', 'KIL', 'BP', 'TRA', 'UX', 'UI', 'DB', 'UPD'];
$high_priority_tags = array_diff($valid_tags, $low_priority_tags);
$release_type = 'minor';

function get_changelog_header(): string
{
    $current_major = get_current_major();
    $version = tiki_version();
    $date = date('Y-m-d');

    return <<<MD
        # Tiki Changelog for Tiki{$version} - {$date}
        
        ------------------
        
        Note: This file is automatically generated. Any manual changes will be overwritten.
        
        ### For the Official Release please visit:
        
        https://doc.tiki.org/Tiki{$current_major}
        
        ### Generate Technical Changelog
        
         ```bash
        php src/ci/generate_changelog.php --help
        ```
        
        ### Below is a summary of the changes included in this release:
        
        ---
        MD;
}

function parse_args(): array
{
    global $valid_tags, $low_priority_tags, $high_priority_tags;

    $args = getopt('', ['expand::', 'only::', 'range::', 'help']);

    if (isset($args['help'])) {
        echo "Usage:\n";
        echo "  php generate_changelog.php [--expand=TAG1,TAG2] [--only=TAG1,TAG2] [--range=FROM..TO]\n\n";
        echo "Description:\n";
        echo "  Generates a changelog from Git history grouped by commit tags.\n\n";

        echo "Default behavior:\n";
        echo "  - All tags are included in the output.\n";
        echo "  - Low-priority sections (" . implode(', ', $low_priority_tags) . ") are automatically collapsed\n";
        echo "    when they contain more than 10 entries.\n";
        echo "  - High-priority sections (" . implode(', ', $high_priority_tags) . ") are always fully displayed, unless restricted by --only.\n\n";
        echo "Options:\n";
        echo "  --expand=TAG1,TAG2\n";
        echo "      Force full display of selected tags, even if they exceed the collapse threshold.\n\n";
        echo "  --range=FROM..TO\n";
        echo "      Use a custom Git range instead of the automatically detected release range.\n\n";
        echo "  --only=TAG1,TAG2\n";
        echo "      Show only the specified tags and hide all others.\n\n";

        echo "Notes:\n";
        echo "  - --expand is most useful for low-priority tags like FIX, REF, TRA.\n";
        echo "  - --only does automatically expand sections even if they are low-priority tags; no need to combine with --expand.\n\n";

        echo "Examples:\n";
        echo "  php generate_changelog.php\n";
        echo "  php generate_changelog.php --expand=FIX\n";
        echo "  php generate_changelog.php --only=NEW,ENH\n";
        echo "  php generate_changelog.php --only=FIX\n";

        echo "Available tags:\n";
        echo "  " . implode(', ', array_filter($valid_tags, fn($t) => $t !== 'BP')) . "\n";

        exit(0);
    }

    $expand = [];
    $only = [];

    if (! empty($args['expand'])) {
        $expand = array_map('trim', explode(',', strtoupper($args['expand'])));
    }

    if (! empty($args['only'])) {
        $only = array_map('trim', explode(',', strtoupper($args['only'])));
    }

    return [
        'expand' => $expand,
        'only'   => $only,
        'range'  => $args['range'] ?? null,
    ];
}


function run($cmd): string
{
    return trim(shell_exec($cmd));
}

function last_tag(): string
{
    run("git fetch --tags");
    return run("git tag --sort=-v:refname | head -n 1");
}

function tiki_version(): string
{
    require_once ROOT . '/lib/setup/twversion.class.php';
    return (new TWVersion())->version;
}

function get_current_major(): int
{
    $current_version = tiki_version();
    return (int) explode('.', $current_version)[0];
}

function detect_release_range(): array
{
    global $release_type;


    $last_tag = last_tag();
    $previous_version = preg_replace('#^tags/#', '', $last_tag);
    $tag_major = (int) explode('.', $previous_version)[0];
    $current_major = get_current_major();
    if ($tag_major === $current_major) {
        $release_type = 'minor';
        return ['type' => 'minor', 'range' => "$last_tag..HEAD"];
    }

    $release_type = 'major';
    $start = get_first_commit_after_branch_point(($current_major - 1) . '.x');

    return ['type' => 'major', 'range' => "$start..HEAD"];
}

function get_first_commit_after_branch_point(string $branch, string $parent = 'master'): string
{
    run("git fetch origin $branch");

    $base = trim(run("git merge-base origin/$branch $parent"));
    $commits = explode("\n", run("git rev-list --reverse $base^..HEAD"));

    return $commits[0] ?? $base;
}

function commits_for_release(?string $range = null): array
{
    if ($range === null) {
        $release = detect_release_range();
        $range = $release['range'];
    }

    echo "Using changelog range: $range" . PHP_EOL;

    $cmd = "git log $range --pretty=format:'%H|%s|%b%x00'";
    return explode("\0", run($cmd));
}
function extract_tags($msg): array
{
    if (preg_match('/^\[([A-Z]+)]/', $msg, $m)) {
        return [$m[1]];
    }
    return [];
}

function extract_mr($body): ?string
{
    // Split into lines
    $lines = preg_split('/\R/', $body);

    // Walk from bottom to top
    for ($i = count($lines) - 1; $i >= 0; $i--) {
        $line = trim($lines[$i]);
        if ($line === '') {
            continue;
        }

        // Match GitLab MR format
        if (preg_match('/!\s*(\d+)/', $line, $m)) {
            return $m[1];
        }
        break;
    }
    return null;
}

function clean_message($msg): string
{
    $msg = strtok($msg, "\n");
    return trim(explode('---', $msg)[0]);
}

function build_groups(array $commits): array
{
    global $valid_tags, $section_map;

    $groups = array_fill_keys(array_keys($section_map), []);

    foreach ($commits as $line) {
        if (! $line) {
            continue;
        }

        $parts = explode('|', $line, 3);
        if (count($parts) < 2) {
            continue;
        }

        [$hash, $subject] = $parts;
        $body = $parts[2] ?? '';

        if (str_starts_with($subject, 'Revert')) {
            continue;
        }

        $tags = extract_tags($subject);
        if (! $tags) {
            continue;
        }

        if ($tags[0] === 'BP') {
            array_shift($tags);
        }

        $tag = $tags[0] ?? null;
        if (! $tag || ! in_array($tag, $valid_tags)) {
            continue;
        }

        if (! isset($groups[$tag])) {
            continue;
        }

        $msg = clean_message($subject);
        $mr = extract_mr($subject . "\n" . $body);
        $hash = trim($hash);
        $url = $mr
            ? REPO_URL . "/-/merge_requests/$mr"
            : REPO_URL . "/-/commit/$hash";

        $ref = $mr ? "!$mr" : substr($hash, 0, 8);

        $groups[$tag][] = "- [$msg ($ref)]($url)";
    }

    return $groups;
}

function filter_groups_by_tags(array $groups, array $only_tags): array
{
    if (empty($only_tags)) {
        return $groups;
    }

    return array_intersect_key($groups, array_flip($only_tags));
}

function render_summary(array $groups, array $options): string
{
    global $section_map, $low_priority_tags, $valid_tags;

    $out = "";

    foreach ($valid_tags as $tag) {
        if (! isset($groups[$tag])) {
            continue;
        }

        $entries = $groups[$tag];
        $count = count($entries);
        if ($count === 0) {
            continue;
        }

        $title = $section_map[$tag];
        $out .= "#### $title - $count\n";

        $force_expand = in_array($tag, $options['expand']) || ! empty($options['only']);
        // Collapse noisy sections
        if (in_array($tag, $low_priority_tags) && $count > 10 && ! in_array($tag, $options['expand'])) {
            $out .= "   Details hidden for readability\n\n";
            $out .= "```sh\n";
            $out .= "   php src/ci/generate_changelog.php --expand=$tag\n\n";
            $out .= "```\n";

            continue;
        }

        foreach ($entries as $entry) {
            $out .= "$entry\n";
        }

        $out .= "\n";
    }

    return $out;
}


$options = parse_args();

$version = tiki_version();
$commits = commits_for_release($options['range']);

$groups = build_groups($commits);
$groups = filter_groups_by_tags($groups, $options['only']);

$output = get_changelog_header() . "\n";
$output .= render_summary($groups, $options);

file_put_contents(CHANGELOG_FILE, $output);

echo "✅ Changelog generated successfully: " . CHANGELOG_FILE . PHP_EOL;

exit(0);
